version: '3.7'

services:
  # Local Redis container
  redis-stream-microservice:
    container_name: redis-stream-microservice
    image: redis:latest
    hostname: redis-local
    ports:
      - "6388:6388"
    # - Double dollars, so that the variable is not expanded by Docker Compose
    # - Surround by quotes, so that the shell does not split the password
    # - The ${variable:?message} syntax causes shell to exit with a non-zero
    #   code and print a message, when the variable is not set or empty
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "beobwoo", "--port", "6388" ]
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/acl/users.acl:/etc/redis/users.acl
